import Link from "next/link";

export function SiteNav() {
  return (
    <header className="border-b border-zinc-200 bg-white/90 backdrop-blur sticky top-0 z-40">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
        <Link href="/" className="flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-700 text-sm font-black text-white">
            N
          </span>
          <div className="leading-tight">
            <div className="text-sm font-black tracking-tight text-zinc-900">
              Nexus Engines
            </div>
            <div className="text-[10px] font-semibold uppercase tracking-widest text-zinc-400">
              Problem → Asset → Stripe
            </div>
          </div>
        </Link>
        <nav className="flex items-center gap-4 text-sm font-semibold text-zinc-600">
          <Link href="/" className="hover:text-zinc-900">
            Catalog
          </Link>
          <Link href="/admin/engines" className="hover:text-zinc-900">
            Admin
          </Link>
        </nav>
      </div>
    </header>
  );
}

export function DisclaimerFooter() {
  return (
    <footer className="mt-auto border-t border-zinc-200 bg-zinc-50">
      <div className="mx-auto max-w-6xl px-4 py-6 text-xs leading-relaxed text-zinc-500">
        <p>
          <strong className="text-zinc-700">Disclaimers:</strong> Outputs
          generated by this platform are for informational, computational, and
          structural blueprint reference only. They do not constitute formal
          legal, financial, medical, tax, or certified engineering advice.
          Consult a licensed professional before production deployment.
        </p>
        <p className="mt-2">
          Operated as a digital information administration service. ©{" "}
          {new Date().getFullYear()} Nexus Engines.
        </p>
      </div>
    </footer>
  );
}
