import Link from "next/link";
import { Suspense } from "react";
import { NavSearch, NavSearchMobile } from "./NavSearch";

export function SiteNav() {
  return (
    <header className="sticky top-0 z-40 border-b border-[#0b1f3a]/10 bg-white/95 backdrop-blur">
      <div className="mx-auto flex max-w-6xl items-center gap-2 px-4 py-3">
        <Link href="/" className="flex shrink-0 items-center gap-2.5">
          <span className="flex h-8 w-8 items-center justify-center rounded-md bg-[#0b1f3a] text-sm font-bold text-[#c9a227]">
            A
          </span>
          <div className="hidden leading-tight sm:block">
            <div className="text-sm font-bold tracking-tight text-[#0b1f3a]">
              Apex Capital
            </div>
            <div className="text-[10px] font-semibold uppercase tracking-widest text-[#0b1f3a]/50">
              Admin Services
            </div>
          </div>
        </Link>

        <Suspense fallback={<div className="mx-3 hidden h-9 flex-1 md:block" />}>
          <NavSearch />
        </Suspense>

        <nav className="ml-auto flex shrink-0 items-center gap-4 text-sm font-medium text-[#0b1f3a]/70 sm:gap-6">
          <Link href="/#catalog-search" className="transition hover:text-[#0b1f3a]">
            Engines
          </Link>
          <Link href="/about" className="hidden transition hover:text-[#0b1f3a] sm:inline">
            About
          </Link>
          <Link href="/admin/engines" className="transition hover:text-[#0b1f3a]">
            Admin
          </Link>
        </nav>
      </div>
      <div className="border-t border-[#0b1f3a]/5 px-4 py-2 md:hidden">
        <Suspense fallback={null}>
          <NavSearchMobile />
        </Suspense>
      </div>
    </header>
  );
}

export function DisclaimerFooter() {
  return (
    <footer className="mt-auto border-t border-[#0b1f3a]/10 bg-[#0b1f3a]">
      <div className="mx-auto max-w-6xl px-4 py-8 text-xs leading-relaxed text-white/60">
        <p>
          <strong className="text-white/90">Disclaimer:</strong> Deliverables
          generated by this platform are provided for informational,
          computational, and structural reference purposes only. They do not
          constitute formal legal, financial, tax, medical, or certified
          engineering advice, and no advisor-client or fiduciary relationship
          is created by their use. Recipients should consult a licensed
          professional before relying on any output for a regulated or
          production decision.
        </p>
        <p className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1 text-white/40">
          <span>
            © {new Date().getFullYear()} Apex Capital Admin Services. All
            rights reserved.
          </span>
          <Link href="/terms" className="transition hover:text-white/70">
            Terms of Service
          </Link>
          <Link href="/privacy" className="transition hover:text-white/70">
            Privacy Policy
          </Link>
          <a
            href="mailto:admin@apexcapitaladmin.com"
            className="transition hover:text-white/70"
          >
            admin@apexcapitaladmin.com
          </a>
        </p>
      </div>
    </footer>
  );
}
